name: shelf_history_api_fallback
description: >
  Fallback to index.html for applications that are using the HTML 5 history API.
version: 0.0.1
author: Jonas kello jonas.kello@gmail.com
homepage: https://www.example.com
dependencies:
  shelf: ">=0.6.1+1 <0.7.0"
dev_dependencies:
  unittest: any
